### ISSUE TITLE
USA Super Smash Bros. Ultimate Text.

### ISSUE THREAD

**Issue by LavaJockey** [Reisyukaku/DeltaLaunch#2]
The USA Super Smash Bros. Ultimate name when shown in DeltaLaunch is in Japanese.

**Comment by BOsborneOfficial** [comment]
This is probably just a title ID issue, the developer will just have to fix SSBU (USA)'s title ID. (Bad grammar for I'm on mobile rn)

Edit: 
> The USA Super Smash Bros. Ultimate name when shown in DeltaLaunch is in Japanese.

I think this issue is fixed but this hasn't been closed. My reasoning for this is that this issue was made a year ago.

**Comment by M0D3RZStudio** [comment]
> This is probably just a title ID issue, the developer will just have to fix SSBU (USA)'s title ID. (Bad grammar for I'm on mobile rn)

I think this issue is fixed but this hasn't been closed cause this issue was made a year ago.

**Comment by LavaJockey** [comment]
Totally forgot about this issue. But yeah deltalaunch lost development a long time ago. Will be closing this issue.
